---
- name: This Playbook Create A Package
  hosts: webservers
  become: true
  tasks:
   - name: Installing a Package
     yum:
      name: ['git','make','gcc','wget','mysql','tree','which','docker','git']
      state: installed      
