---
- name: This Playbook Create A Package
  hosts: webservers
  become: true
  tasks:
   - name: Installing httpd Package
     yum:
      name: httpd
      state: installed
     when: ansible_os_family == "RedHat"   
  
   - name: Starting Httpd  Service
     service:
       name: httpd 
       state: started      
     when: ansible_os_family == "RedHat"

   - name: Installing apache2 Package
     apt:
      name: apache2
      state: present
     when: ansible_os_family == "Debian"  

   - name: Starting apache2  Service
     service:
       name: apache2
       state: started
     when: ansible_os_family == "Debian"
